#!/bin/bash
set -x

echo "Prepack shell script"

CWD=$(pwd)
TEMPLATE_PATH="${CWD}/template.tar"
EDGE_BOILERPLATE_PATH="${CWD}/../edge-boilerplate"

if [ ! -d "${EDGE_BOILERPLATE_PATH}" ]; then
  echo "${EDGE_BOILERPLATE_PATH} does not exist"
  exit 1
fi

cd ${EDGE_BOILERPLATE_PATH}
tar -cf "${TEMPLATE_PATH}" .
cd "${CWD}"
