#!/usr/bin/env node
/* eslint-disable */

const path = require("path")
const fs = require("fs")

const tar = require("tar")

console.log("prepack node script")

const CWD = process.cwd()
const TEMPLATE_PATH = path.join(CWD, "template.tar")
const EDGE_BOILERPLATE_PATH = path.join(CWD, "..", "edge", "packages", "edge-boilerplate")

try {
  fs.accessSync(EDGE_BOILERPLATE_PATH, fs.constants.R_OK)
} catch (error) {
  console.error(`Path ${EDGE_BOILERPLATE_PATH} is not accessible`)
  console.error("The edge git repo should be placed beside the edge-create repo")
  process.exit(2)
}

tar
  .create(
    {
      file: TEMPLATE_PATH,
      cwd: EDGE_BOILERPLATE_PATH,
      follow: true
    },
    ["."]
  )
  .then(() => {
    console.log("template.tar created")
    process.exit(0)
  })
  .catch((error) => {
    console.error(error.stack)
    process.exit(1)
  })
